// src/app/components/shared/buttons/floating-button/floating-button.component.ts
import { Component, ElementRef, EventEmitter, Input, Output } from '@angular/core';

@Component({
    selector: 'floating-button',
    templateUrl: './floating-button.component.html',
})
export class FloatingButton {
    @Input('href')
    href: string = ''
    @Output() click = new EventEmitter();
}

<a (click)="click.emit()"><ng-content /></a>

<style lang="scss">
  a {
    color: hsl(0, 0%, 97%);
    transition-duration: 0.2s;
    text-decoration: none;
    text-transform: uppercase;
    line-height: 3.1rem;
    cursor: pointer;
  }
  a:hover {
    color: hsl(342, 40%, 18%);
  }
</style>

// src/lib/components/buttons/FloatingButton.svelte
<script>
	/**
	 * @type string
	 */
	export let href;
</script>

<div>
	<a {href}><slot /></a>
</div>

<style>
	a {
		color: var(--luminous-white);
		transition-duration: 0.2s;
		text-decoration: none;
		text-transform: uppercase;
		line-height: 3.1rem;
	}
	a:hover {
		color: var(--primary-orange);
	}
</style>
