// src/app/components/game/results/results.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { GameStatus } from 'api/interfaces/GameInterfaces';
import GameController from 'src/controllers/GameController';

@Component({
  selector: 'app-results',
  templateUrl: './results.component.html',
  styleUrls: ['./results.component.scss']
})
export class ResultsComponent implements OnInit {
  @Input('gameController')
  gameController!: GameController;
  lowest = 0
  highest = 0
  average = 0
  ngOnInit() {
    this.lowest = this.gameController.gameInfos!.actualVotes.map((vote) => Number(vote.value))?.sort((a, b) => a - b)[0];
    this.highest = this.gameController.gameInfos!.actualVotes.map((vote) => Number(vote.value))?.sort((a, b) => b - a)[0];
    this.average = this.gameController.gameInfos!.actualVotes.map((vote) => Number(vote.value))?.reduce((a, b) => a + b, 0) / this.gameController.gameInfos!.actualVotes?.length;
  }



  gameStatus: typeof GameStatus = GameStatus
}

<div style="display:flex;justify-content:space-around;gap:2vw;text-align:center;">
	<div>
		<app-card [fontSize]="2" [number]="lowest!.toString()" width="15vw" />
		<h1><b>MENOR</b></h1>
	</div>
	<div>
		<app-card [fontSize]="2" [number]="average!.toString()" width="15vw" />
		<h1><b>MÉDIA</b></h1>
	</div>
	<div>
		<app-card [fontSize]="2" [number]="highest!.toString()" width="15vw" />
		<h1><b>MAIOR</b></h1>
	</div>
</div>

// src/lib/components/gameComponents/Results.svelte
<script lang="typescript">
	import type GameController from '$lib/controllers/GameController';
	import type { IGameInfos } from '$lib/interfaces/GameInterfaces';
	import Card from './card/Card.svelte';

	export let gameController: GameController;
	let gameInfos: IGameInfos | undefined;
	gameController.gameInfos.subscribe((infos) => (gameInfos = infos));

	$: lowest = gameInfos!.actualVotes.map((vote) => Number(vote.value))?.sort((a, b) => a - b)[0];
	$: highest = gameInfos!.actualVotes.map((vote) => Number(vote.value))?.sort((a, b) => b - a)[0];
	$: average =
		gameInfos!.actualVotes.map((vote) => Number(vote.value))?.reduce((a, b) => a + b, 0) /
		gameInfos!.actualVotes?.length;
</script>

<div style="display:flex;jusitfy-content:space-around;gap:2vw;text-align:center;">
	<div>
		<Card fontSize={2} number={lowest?.toString()} width="15vw" />
		<h1><b>MENOR</b></h1>
	</div>
	<div>
		<Card fontSize={2} number={average?.toString()} width="15vw" />
		<h1><b>MÉDIA</b></h1>
	</div>
	<div>
		<Card fontSize={2} number={highest?.toString()} width="15vw" />
		<h1><b>MAIOR</b></h1>
	</div>
</div>
